#!/bin/bash
writeblog=$PWD
publicblog=../wkevin.github.io

git pull
if [ $? -ne 0 ]; then
exit 1
fi

echo ===== hexo general =====
hexo g

echo 
echo ===== git pull in $publicblog =====
cd $publicblog
git pull

if [ $? -ne 0 ]; then
exit 1
fi

echo 
echo ===== copy public from writeblog to publicblog =====
cp -R $writeblog/public/. ./

git status
echo 
echo ==========
echo "Do you want to git add-commit-push?...(y or n)"
read reply leftover
case $reply in
    y* | Y*)
        git add .
        git commit -m "Deploy by wkevin manu from hexo"
        git push origin master:master;;
    *)
        echo "Happy to you!";;
esac

echo 
echo ==========
cd -
echo ==========

git status
echo
echo
echo ============================================
echo Dont forget git commit and push write branch 
echo ============================================
echo
echo

