menu:
  首页: /
  存档: /archives/
  关于: /about/
  订阅: /atom.xml
  书法: /penmanship/
  链接: /freqlink/

widgets: 
- menu
- category
- tagcloud
- freqlink

excerpt_link: Read More

fancybox: true

# 友言评论
UYUserId: 1928643

# cnzz统计
cnzzId:

# JiaThis分享
jiathisUUID:

weibo:
	name: wkevin27
	uid: wkevin27
	link: http://weibo.com/wkevin27

rss: http://xxx.xx/atom.xml
